sudo: required
services:
  - docker

before_install:
  - docker build -t vagrant/docker-react -f Dockerfile.dev .

script:
  - docker container run -e CI=true vagrant/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-166973457534"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY